let books=[];let statusFilter="",sortBy="recent",editIndex=null,tempCover="";

async function loadBooks(){try{const r=await fetch("/api/books",{cache:"no-store"});if(!r.ok)throw new Error("load failed");const data=await r.json();books=Array.isArray(data)?data:[];}catch(_){books=[];}render();}
async function save(){try{await fetch("/api/books",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(books)});}catch(_){alert("Impossible de sauvegarder sur le serveur pour le moment.");}}
function esc(s){return(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
function stars(n){return n?"★".repeat(n)+"☆".repeat(5-n):"☆☆☆☆☆";}
function fakeCover(b){return `<div class="fake-cover"><div class="fake-author">${esc(b.author||"Auteur")}</div><div class="fake-title">${esc(b.title||"Sans titre")}</div><div class="fake-mark">BIBLIOTHÈQUE D’ELSA</div></div>`;}
function applyTheme(){const theme=localStorage.getItem("elsa-theme")||"dark";document.body.classList.toggle("light",theme==="light");const label=document.getElementById("themeLabel");if(label)label.textContent=theme==="light"?"☀️ Mode clair":"🌙 Mode sombre";}
function toggleTheme(){localStorage.setItem("elsa-theme",document.body.classList.contains("light")?"dark":"light");applyTheme();}
function openModal(i=null){editIndex=i;modal.classList.add("on");modalTitle.textContent=i===null?"Ajouter un livre":"Modifier le livre";const b=i===null?{title:"",author:"",status:"À lire",rating:0,note:"",cover:""}:books[i];t.value=b.title||"";a.value=b.author||"";st.value=b.status||"À lire";rt.value=b.rating||0;note.value=b.note||"";coverUrl.value=(b.cover&&b.cover.startsWith("http"))?b.cover:"";tempCover=b.cover||"";updatePreview();}
function closeModal(){modal.classList.remove("on");editIndex=null;tempCover="";}
function updatePreview(){preview.innerHTML=tempCover?`<img src="${tempCover}">`:"Aperçu de la couverture";}
function chooseCover(){coverUpload.click();}
coverUpload.onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{tempCover=reader.result;coverUrl.value="";updatePreview();};reader.readAsDataURL(file);};
coverUrl.oninput=()=>{tempCover=coverUrl.value.trim();updatePreview();};
function saveBook(){if(!t.value.trim()){alert("Ajoute au moins le titre 😊");return;}const b={title:t.value.trim(),author:a.value.trim(),status:st.value,rating:+rt.value,note:note.value.trim(),cover:tempCover,added:editIndex===null?Date.now():books[editIndex].added};if(editIndex===null)books.unshift(b);else books[editIndex]=b;save();render();closeModal();}
function deleteBook(i){if(confirm("Supprimer ce livre ?")){books.splice(i,1);save();render();}}
function updateBookStatus(i,status){if(!books[i])return;books[i].status=status;save();render();}
function setStatus(s){statusFilter=s;render();}
function toggleAuthor(){if(typeof authorPanel!=="undefined")authorPanel.style.display=authorPanel.style.display==="none"?"block":"none";}
function setAuthorSearch(v){authorFilter.value=v||"";const a=document.getElementById("authorSearch"),m=document.getElementById("mobileAuthorSearch");if(a&&a.value!==v)a.value=v;if(m&&m.value!==v)m.value=v;render();}
function render(){const q=search.value.toLowerCase(),au=authorFilter.value.toLowerCase();let arr=books.map((b,i)=>({...b,_i:i})).filter(b=>(!statusFilter||b.status===statusFilter)&&(!au||(b.author||"").toLowerCase().includes(au))&&(!q||(b.title+" "+b.author).toLowerCase().includes(q)));arr.sort((a,b)=>sortBy==="title"?a.title.localeCompare(b.title):sortBy==="author"?a.author.localeCompare(b.author):sortBy==="rating"?(b.rating||0)-(a.rating||0):(b.added||0)-(a.added||0));grid.innerHTML=arr.length?arr.map(b=>`<article class="book"><div class="cover">${fakeCover(b)}${b.cover?`<img src="${esc(b.cover)}" onerror="this.remove()">`:""}</div><div class="info"><div class="title">${esc(b.title)}</div><div class="author">${esc(b.author)}</div><div class="stars">${stars(b.rating)}</div><span class="badge">${esc(b.status)}</span><select class="status-select" onchange="updateBookStatus(${b._i},this.value)"><option ${b.status==="À lire"?"selected":""}>À lire</option><option ${b.status==="En cours"?"selected":""}>En cours</option><option ${b.status==="Lu"?"selected":""}>Lu</option><option ${b.status==="Wishlist"?"selected":""}>Wishlist</option></select><div class="cardBtns"><button onclick="openModal(${b._i})">Modifier</button><button onclick="deleteBook(${b._i})">Supprimer</button></div></div></article>`).join(""):`<div class="empty">Aucun livre pour le moment.<br><br>Clique sur “+ Ajouter” pour commencer ta bibliothèque 📚</div>`;update();}
function update(){count.textContent=books.length;totalMini.textContent=books.length;sTotal.textContent=books.length;sRead.textContent=books.filter(b=>b.status==="Lu").length;sCourse.textContent=books.filter(b=>b.status==="En cours").length;sWish.textContent=books.filter(b=>b.status==="Wishlist").length;sAuthors.textContent=new Set(books.map(b=>b.author).filter(Boolean)).size;}
function exportData(){const blob=new Blob([JSON.stringify(books,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ma-bibliotheque-elsa.json";a.click();}
if("serviceWorker"in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{});}
applyTheme();loadBooks();
